#PBS -N MATLAB 
#PBS -o out.$PBS_JOBID
#PBS -e err.$PBS_JOBID
#PBS -l nodes=2:ppn=10
#PBS -q fat82
source /lustre/soft/intel2015/composer_xe_2015/bin/compilervars.sh intel64
source /lustre/soft/intel2015/mkl/bin/intel64/mklvars_intel64.sh
source /lustre/soft/intel2015/impi/5.0.2.044/bin64/mpivars.sh

cd $PBS_O_WORKDIR
cat "$PBS_NODEFILE"
NP=$(wc -l < "$PBS_NODEFILE")

mpirun -np $NP -machinefile  ${PBS_NODEFILE} /lustre/soft/MATLAB/R2015b/bin/matlab -nodesktop  -nodisplay < /home/inspur/20170711matlab/matlab_test/test_zw.m
