#!/bin/bash
#----------------------------------------------------------
# This script is used to automatically clean up some useless 
# files generated during neb calculations. At the same time 
# a folder used for calculations will be regenerated.
#----------------------------------------------------------
echo "Please wait..."

path=$1
path=${path%/}

# If the folder don't match, exit.
if [ ! -d "$path" ]; then
    echo "Error: $path folder not found."
    exit 1
fi

# If the folder used to store path backups does not exist, create it.
if [[ ! -d "$path.bak" ]]
then
    mkdir "$path".bak
fi

# Backup path and backup number automatically updated.
i=1
for backup in "$path".bak/*
do  
    [[ -e "$backup" ]] || break
    i=$((i+1))
done
cp -r "$path" "$path".bak/"$path".bak$i 2> /dev/null

# Copy CONTCAR to POSCAR. And remove the output file.
cd "$path"||exit

# Remove the file generated by nebresults.pl.
rm -rf movie* vaspgr ./*.* 2> /dev/null

# For fixing the two points in the elastic band.
folders=(0*/)
# If the folder don't match, exit.
if [ ${#folders[@]} -eq 0 ]; then
    echo "No images in the folder."
    exit 1
fi

# remove the slash, leave the name of folder.
folders=("${folders[@]%/}")

# Extrate the maximum folder number.
max_n=0
for dir in "${folders[@]}"; do
    num=${dir#0}  # remove the prefix 00-
    if [[ $num =~ ^[0-9]+$ ]]; then
        (( num > max_n )) && max_n=$num
    fi
done

cp ini/CONTCAR 00/POSCAR 2> /dev/null
cp fin/CONTCAR 0"$max_n"/POSCAR 2> /dev/null

# Clean the useless file.
i=1
for image in [0-9]*
do
    cd "$image"||exit
    rm ./*.* stdout 2> /dev/null
    if [[ -f CONTCAR ]]
    then
        cp CONTCAR POSCAR
    fi
    cd ..
done

echo "Clean&Generate Finished."