#!/bin/bash
#----------------------------------------------------------
# This script is used to automatically clean up some useless 
# files generated during neb calculations. At the same time 
# a folder used for calculations will be regenerated.
#----------------------------------------------------------
echo "Please wait..."

# If the folder used to store path backups does not exist, create it.
if [[ ! -d "path$1.bak" ]]
then
    mkdir path"$1".bak
fi

# Backup path and backup number automatically updated.
i=1
for backup in path"$1".bak/*
do  
    [[ -e "$backup" ]] || break
    i=$((i+1))
done
cp -r path"$1" path"$1".bak/path"$1".bak$i 2> /dev/null

# Change CONTCAR to POSCAR. And remove the output file 
# generated by nebresults.pl.
cd path"$1"||exit
rm -rf movie* vaspgr ./*.* 2> /dev/null
i=1
for image in [0-9]*
do
    cd "$image"||exit
    rm ./*.* stdout 2> /dev/null
    if [[ -f CONTCAR ]]
    then
        cp CONTCAR POSCAR
    fi
    cd ..
done
echo "Clean&Generate Finished."