#!/bin/bash
#----------------------------------------------------------
# This script is used to automatically clean up some useless 
# files generated during neb calculations. At the same time 
# a folder used for calculations will be regenerated.
#----------------------------------------------------------

# Read the path to be backed up from stdin.
read -rp 'Please enter a number like "1" to assign a path to backup: ' N
echo "Please wait..."

# If the folder used to store path backups does not exist, create it.
if [ ! -d "path$N.bak" ]
then
    mkdir path"$N".bak
fi

# Backup path and backup number automatically updated.
# Max image number: 10
i=1
while [ $i -lt 10 ]
do
    if [ ! -d path"$N".bak/path"$N".bak"$i" ]
    then
    cp -r path"$N" path"$N".bak/path"$N".bak$i
    echo "The path$N.bak$i was backuped in path$N.bak."
    break
    else    
        i=$((i+1))
    fi
done

# Change CONTCAR to POSCAR. And remove the output file 
# generated by nebresults.pl.
cd path"$N"||exit
rm -rf movie* vaspgr ./*.* 2> /dev/null
i=1
while [ $i -lt 10 ]
do
    if [ -d 0$i ]
    then
        cd 0$i||exit
        rm ./*.* stdout 2> /dev/null
        if [ -f CONTCAR ]
        then
            cp CONTCAR POSCAR    
        fi
        cd ..
    i=$((i+1))
    else
        echo "Clean&Generate Finished."    
        break
    fi
done